name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Java Testing
      id: java-testing
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Java Testing
        setup-command: ''
        command: gradle test
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        JAVA-TESTING_RESULTS: "${{steps.java-testing.outputs.result}}"
      with:
        runners: java-testing
